spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cl_log_api_server?characterEncoding=UTF-8
    username: root
    password: 1234

decorator:
  datasource:
    p6spy:
      enable-logging: true
